### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [VPN-Subcription-Links/ClashX-V2Ray-TopFreeProxy#16]
### Description:

In the "ClashX-V2Ray-TopFreeProxy/combine/combine.py", I have identified a security vulnerability about insecure SSL/TLS Verification and configuration. Bypassing certificate verification or accepting all host names are considered insecure.

### Location:

https://github.com/VPN-Subcription-Links/ClashX-V2Ray-TopFreeProxy/blob/main/combine/combine.py#L40

```python
resp: requests.Response = requests.get(url, verify=False, timeout=10)
```

### Reference

- **CWE-295: Improper Certificate Validation**

### Recommendations:

Use SSL/TLS protocol with proper verification.

**Comment by WilliamStar007** [comment]
thanks for the recommendation
feel free to reopen this issue with a pull request
